### ISSUE TITLE
Spezifikation für AMG zum Einbau der UUIDs in das MBZ erstellen

### ISSUE THREAD

**Issue by philgei** [ProjektAdLer/MoodlePluginLocal#21]
Damit das AMG die UUIDs in das MBZ übertragen kann, muss dazu

- [ ] Eine WIki Seite mit der Spiezifikation dazu erstellt werden
- [ ] Diese an das AMG Team übergeben werden

**Comment by Glutamat42** [comment]
spezifikation https://wiki.projekt-adler.eu/de/MoodlePlugin/mbz-format
kann zu?
