### ISSUE TITLE
AdLer Rollen definieren

### ISSUE THREAD

**Issue by philgei** [ProjektAdLer/MoodlePluginLocal#27]
Es soll eine AdLer manager rolle geben welche nur Kurse hochladen und löschen kann. 

Dazu: 

- Muss eine minimale Rolle erstelle werden
- Dem AdLer User die Teacher rolle bei seinem eigenen Kurs entzogen werden
- Dem User die Rolle "Editing Teacher" zuweisen

**Comment by Glutamat42** [comment]
Anforderungen von alter Issue #24 

```
Adler manager rolle definieren und automatisch anlegen.

    Minimierte Berechtigungen
        Kurs hochladen und löschen in seiner Adler Kategorie (Neuer api enpoint mit eigener capability hierfür)
        per default NICHT berechtigt in default kategorie (möglicherweise erteilt das plugin derzeit diese Berechtigung)
        Darf Kurselemente NICHT bearbeiten, löschen, anlegen in Adler Kursen
        Darf NICHT Kurse erstellen/löschen/bearbeiten in seiner Adler Kategorie über moodle UI
```

**Comment by Glutamat42** [comment]
Vermutlich sollten adler manager auch gewissen auswertungsberechtigungen haben um den Lernfortschritt der Teilnehmer in Moodle einsehen zu können

**Comment by philgei** [comment]
Dazu wird dem Nutzer dann die Roller "Ediuting Teacher" zugewiesen

**Comment by Glutamat42** [comment]
Nicht non editing?

**Comment by Glutamat42** [comment]
<inherit>moodle/course:delete</inherit>
        <inherit>moodle/course:enrolconfig</inherit>
        <inherit>moodle/question:add</inherit>
        <inherit>moodle/question:managecategory</inherit>
        <inherit>moodle/restore:configure</inherit>
        <inherit>moodle/restore:restoreactivity</inherit>
        <inherit>moodle/restore:restorecourse</inherit>
        <inherit>moodle/restore:restoresection</inherit>
        <inherit>moodle/restore:restoretargetimport</inherit>
        <inherit>moodle/restore:rolldates</inherit>
        <inherit>moodle/restore:uploadfile</inherit>
        <inherit>moodle/restore:userinfo</inherit>
        <inherit>moodle/restore:viewautomatedfilearea</inherit>

**Comment by Glutamat42** [comment]
evaluieren: separate permission zum erstellen eines adler kurses, um dem user nicht generell die restore permission zuweisen zu müssen

**Comment by Glutamat42** [comment]
Done
